import React from 'react';
import {Composition} from 'remotion';
import {AutoPreviewScene} from './AutoPreviewScene';
import { theme } from '../../theme';

export const GeneratedPreviewCompositions = () => (
  <>
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/01-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/01-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/02-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/02-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/03-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/03-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/04-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/04-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/07-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/07-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/10-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/10-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/11-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/11-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/14-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/14-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/15-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/15-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/16-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/16-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/17-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/17-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/18-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/18-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/20-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/20-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/21-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/21-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/23-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/23-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/26-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/26-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/27-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/27-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/29-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/29-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/30-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/30-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/31-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/31-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/32-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/32-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/36-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/36-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/37-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/37-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/40-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/40-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/43-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/43-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/44-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/44-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/45-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/45-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/46-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/46-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/47-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/47-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/48-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/48-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/50-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/50-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/51-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/51-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/52-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/52-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/53-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/53-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/58-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/58-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/59-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/59-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/60-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/60-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/61-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/61-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/62-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/62-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/63-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/63-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/64-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/64-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/65-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/65-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/66-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/66-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/73-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/73-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/74-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/74-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/77-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/77-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/79-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/79-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/80-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/80-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/81-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/81-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/82-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/82-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/83-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/83-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/84-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/84-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/85-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/85-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/86-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/86-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/92-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/92-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/93-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/93-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/94-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/94-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/95-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/95-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/96-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/96-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/98-preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/98-preview.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/index" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/index.html" } as any} />
    <Composition id="episodes/02-ftx/assets/custom-graphics/previews/opening_preview" component={AutoPreviewScene} durationInFrames={180} fps={theme.animation.fps} width={theme.animation.width} height={theme.animation.height} defaultProps={{ previewPath: "/episodes/02-ftx/assets/custom-graphics/previews/opening_preview.html" } as any} />
  </>
);